### ISSUE TITLE
SDK里面没有找到安全组关联虚拟机、与虚拟机解除关联的接口

### ISSUE THREAD

**Issue by sunkangke** [huaweicloud/huaweicloud-sdk-java-v3#10]
SDK里面没有找到安全组关联虚拟机、与虚拟机解除关联的接口

**Comment by xionghao-hw** [comment]
你好，3.0.7-beta版本提供相关接口：
ecsClient.novaAssociateSecurityGroup();
ecsClient.novaDisassociateSecurityGroup();
