### ISSUE TITLE
使用okhttp3不当导致线程数一直增加的bug

### ISSUE THREAD

**Issue by wangko27** [huaweicloud/huaweicloud-sdk-java-v3#11]
## 问题: 使用okhttp3不当导致线程数一直增加的bug

> 按照目前的代码逻辑，那么我每次在构建不同的Client(EcsClient, VpcClient等)时，最终都会创建一个OkHttpClient，该类默认会创建5个线程大小的线程池，那么如果在加上多个(AKSK)账号 + 加上不同区域,这种方式创建的线程池没多久就上几万个线程了

在代码HcClient.java中的83行,和DefaultHttpClient中导致该bug
```java
 httpClient = new DefaultHttpClient(this.httpConfig);
```
```java
public class DefaultHttpClient implements HttpClient {
    private OkHttpClient client = new OkHttpClient();
    private HttpConfig httpConfig;

    public DefaultHttpClient(HttpConfig httpConfig) {
        withHttpConfig(httpConfig);
    }
    public HttpConfig getHttpConfig() {
        return httpConfig;
    }
```
影响版本：所有

解决办法 就是把创建OkHttpClient 跟HttpConfig的方式传入，给用户自己定义

**Comment by xionghao-hw** [comment]
你好，感谢提问，我们正在分析该问题，谢谢

**Comment by xionghao-hw** [comment]
你好，3.0.14版本已经设置了线程上限，暂时未开放修改线程数方法，可以先试试看，谢谢
