### ISSUE TITLE
调用接口时，{project_id}没有替换

### ISSUE THREAD

**Issue by lidisi8520** [huaweicloud/huaweicloud-sdk-java-v3#12]
如题，在调用接口时，
![image](https://user-images.githubusercontent.com/39178394/93306492-84e6e880-f832-11ea-805d-412ec928e25d.png)
这个project_id没有替换成传入进去的参数，用了主页上面的实例代码，也是无法替换，希望寻求帮助。谢谢

**Comment by lidisi8520** [comment]
不知道这个原因是bug的问题还是我构造参数时候没有做对，
![image](https://user-images.githubusercontent.com/39178394/93307051-2837fd80-f833-11ea-99a0-8e69afe980bd.png)
这个是我构造参数的代码。
![image](https://user-images.githubusercontent.com/39178394/93307226-53225180-f833-11ea-9710-ffacef9dcf3d.png)
这个地方是异常xnxi信息。请帮忙看一下，谢谢

**Comment by Huaweicloud-SDK** [comment]
您好，这边帮您看了一下，你这边的endpoint没有填写协议，此处修改为

**Comment by Huaweicloud-SDK** [comment]
您好，您这边的异常原因是endpoint配置有误，请按照如下方式配置：

**Comment by Huaweicloud-SDK** [comment]
您好，您这边的异常原因是endpoint配置有误，请修改为如下配置：
``` java
String endpoint = "https://ecs.cn-north-4.myhuaweicloud.com";
```

另外，project_id没有替换，是因为代码这里的调用顺序是这样的：
1. 构造原始HttpRequest，此处endpoint没有配置协议直接抛出异常
2. 检查BasicCredentials是否配置了projectId，如果没有配置就抛出异常，如果配置了就进行替换
所以您这里是因为前一步失败了，所以您看到project_id没有替换。

**Comment by lidisi8520** [comment]
好的，谢谢。解决了。
