### ISSUE TITLE
调用/v3/projects接口，不传project_id无法通过

### ISSUE THREAD

**Issue by lidisi8520** [huaweicloud/huaweicloud-sdk-java-v3#13]
调用iam中的keystoneListProjects方法，在类BasicCredentials中没有构造projectId，请求无法通过，这个接口是查询指定条件下的项目列表，我要查询出项目id，为什么还要传这个id呢，这个算bug吗？

**Comment by xionghao-hw** [comment]
IAM为全局服务，请参考这个：
