### ISSUE TITLE
V3版本对应的example都没有吗？

### ISSUE THREAD

**Issue by zhouxw536** [huaweicloud/huaweicloud-sdk-java-v3#14]

**Comment by wuchen-huawei** [comment]
你好，以VPC服务ListVpcs接口为例的demo样例在本仓库Readme.md中有完整样例；
另外，V3版本的demo样例可以在api explorer上面查看，目前已经可以直接查看demo样例的服务有：ECS（弹性云服务器） / VPC（虚拟私有云） / EIP（弹性公网IP） / IoTDA（设备接入）

API explorer链接：https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=ECS&api=ListServersDetails
