### ISSUE TITLE
apiexplorer里的/v2.1/{project_id}/flavors/detail接口，为啥SDK里没有提供API？

### ISSUE THREAD

**Issue by zhouxw536** [huaweicloud/huaweicloud-sdk-java-v3#15]

**Comment by suchangshi** [comment]
您好，后续版本会把该接口添加到sdk，可以先使用 /v1/{project_id}/cloudservers/flavors。
https://support.huaweicloud.com/api-ecs/zh-cn_topic_0020212656.html
