### ISSUE TITLE
SDK和API Explorer中没有找到物联网设备接入的可选配置中自定义Topic的相关接口

### ISSUE THREAD

**Issue by sunkangke** [huaweicloud/huaweicloud-sdk-java-v3#18]
SDK和API Explorer中没有找到设备接入的可选配置中自定义Topic的相关接口
![image](https://user-images.githubusercontent.com/41261901/97266567-a42a5a00-1863-11eb-8c53-b5c56f5929b6.png)

**Comment by we5god** [comment]
> SDK和API Explorer中没有找到设备接入的可选配置中自定义Topic的相关接口
> ![image](https://user-images.githubusercontent.com/41261901/97266567-a42a5a00-1863-11eb-8c53-b5c56f5929b6.png)

为什么不提供自定义topic接口？
Ans：IoTDA服务计划提供完全灵活的topic能力，即不需要提前在产品中定义topic，只需要符合一定格式规范就可以使用任意topic与设备通信，因此产品中的自定义topic功能将不再必要，后续将在合适时间去掉该功能，用户直接使用自己的topic与设备通信即可，所以这里不提供API管理自定义topic；目前无需预先定义的灵活topic能力已经上线，资料预计在11月开放。
