### ISSUE TITLE
SMN(Simple message notification) support  in huaweicloud-sdk-java-v3

### ISSUE THREAD

**Issue by mathewsreji** [huaweicloud/huaweicloud-sdk-java-v3#20]
Is there a plan to support Huawei-cloud SMN in the v3 SDK? I am trying to build an apache-camel component for Huawei cloud SMN services. Any clues around this would be helpful

Cheers
Reji

**Comment by mathewsreji** [comment]
Hello @glovethu @wuchen-huawei @xionghao-hw @zoupengli  
Just a gentle follow up to know more on the plans for SDK for SMN services.  This is Reji Mathews from Huawei R&D , Toronto.

**Comment by xionghao-hw** [comment]
Hello, new version 3.0.24-beta support smn ,ths
