### ISSUE TITLE
Include service endpoint resolver inside the core module

### ISSUE THREAD

**Issue by mathewsreji** [huaweicloud/huaweicloud-sdk-java-v3#22]
Its beneficial to have an endpoint URL resolver in the core module for each of the supported cloud services. Based on the region and service name, it can construct endpoints as listed on https://developer.huaweicloud.com/en-us/endpoint. 

Similar resolver in the older version of the SDK  at https://github.com/huaweicloud/huaweicloud-sdk-java/blob/master/core/src/main/java/com/huawei/openstack4j/openstack/identity/internal/AKSKEndpointURLResolver.java

**Comment by xionghao-hw** [comment]
Hi, you can try new feature.

4.2 Specify Region when initializing {Service}Client (Recommended)

// Initialize specified service client instance, take IamClient for example
IamClient iamClient = IamClient.newBuilder()
    .withHttpConfig(config)
    .withCredential(credentials)
    .withRegion(IamRegion.CN_NORTH_4)
    .build();
