### ISSUE TITLE
BUG : SMN - PublishMessageRequestBody object is invalid as per api spec

### ISSUE THREAD

**Issue by mathewsreji** [huaweicloud/huaweicloud-sdk-java-v3#24]
- As per the [api spec document](https://support.huaweicloud.com/en-us/api-smn/smn_api_54003.html) for smn publish message using a template, the tags parameters should be a valid Map object. 
![image](https://user-images.githubusercontent.com/5595781/102526353-86aa8d00-4069-11eb-8df4-c9282f099ee4.png)

- Currently, in the SDK code, inside the model object [PublishMessageRequestBody](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/services/smn/src/main/java/com/huaweicloud/sdk/smn/v2/model/PublishMessageRequestBody.java#L47-L50), its set as List<String> which fails when used in our application
![image](https://user-images.githubusercontent.com/5595781/102526292-74305380-4069-11eb-96b9-9fb53ce1bec3.png)

- FIX : needs to be converted to java.util.Map object or equivalent

**Comment by mathewsreji** [comment]
Fix available via PR - https://github.com/huaweicloud/huaweicloud-sdk-java-v3/pull/25

**Comment by xionghao-hw** [comment]
Hi, this problem has fixed in 3.0.29-beta.

**Comment by mathewsreji** [comment]
> Hi, this problem has fixed in 3.0.29-beta.

Thanks for the fix
