### ISSUE TITLE
Not work connection to the https proxy

### ISSUE THREAD

**Issue by DaulGitHub** [huaweicloud/huaweicloud-sdk-java-v3#26]
We use https proxy, on proxy_url:proxy_port
When executing, I get an error ConnectionException

This code not work for me

        val config = HttpConfig.getDefaultHttpConfig()
		.withTimeout(8000)
		.withIgnoreSSLVerification(true)
		.withProxyHost(proxy_url)
		.withProxyPort(proxy_port)
		.withProxyUsername(proxy_login)
		.withProxyPassword(proxy_password)
		.addHttpListener(HttpListener.forRequestListener {
		println(
			"REQUEST: ${it.httpMethod()} ${it.uri()} ${it.headers().map { kv -> "${kv.key} : ${kv.value}"}.joinToString(";")} ${it.body() ?: ""}"
		)
	})

	val credentials = BasicCredentials()
		.withAk(ak)
		.withSk(sk)
		.withProjectId(projectId)

	val ctsClient = CtsClient.newBuilder()
		.withHttpConfig(config)
		.withCredential(credentials)
		.withEndpoint(ctsEndpoint)
		.build()

	val vpcClient = VpcClient.newBuilder()
		.withHttpConfig(config)
		.withCredential(credentials)
		.withEndpoint(vpcEndpoint)
		.build()

	println("VPC Service: listVpcs request was started")
	val listVpcsResponse: ListVpcsResponse = vpcClient.listVpcs(ListVpcsRequest().withLimit(1))
	println("VPC Service: the request was completed successfully")
	println("response is: $listVpcsResponse")

	println("CTS Service: listTraces request was started")
	val response = ctsClient.listTraces(ListTracesRequest().withTraceType(ListTracesRequest.TraceTypeEnum.SYSTEM))
	println("CTS Service: the request was completed successfully")
	println("response is: $response")
}

**Comment by wuchen-huawei** [comment]
Sorry to tell you that our SDK doesn't support https proxy now, `OkHttp` is used as our middleware, and this issue hasn't been resolved by OkHttp, you could refer to [HTTPS proxy is not supported](https://github.com/square/okhttp/issues/3787). 

We’ve looked up for related issues, maybe you could see if [this issue](https://github.com/square/okhttp/issues/6561) would solve your problem.

If you have any other questions, please leave a message on this issue. We'll try to handle it as soon as possible.

**Comment by DaulGitHub** [comment]
Thank you Wuchen!)
