### ISSUE TITLE
Not found obs client

### ISSUE THREAD

**Issue by DaulGitHub** [huaweicloud/huaweicloud-sdk-java-v3#27]
I didn't find the obs service in the list of available services
I looked here https://github.com/huaweicloud/huaweicloud-sdk-java-v3/tree/master/services
How to work with the obs service using huaweicloud-sdk-java-v3 ?

**Comment by wuchen-huawei** [comment]
OBS client in huaweicloud-sdk-java-v3 is on the way, if you want to use it right now, you could refer to [huaweicloud-sdk-java-obs](https://github.com/huaweicloud/huaweicloud-sdk-java-obs) first.

**Comment by mawenbo-huawei** [comment]
OBS is supported (3.1.43 and later).
