### ISSUE TITLE
ShowReposResp size属性类型是Integer 镜像一大就会报错

### ISSUE THREAD

**Issue by ridewind** [huaweicloud/huaweicloud-sdk-java-v3#28]
如题 api的size应该是字节数 用int接的话 超过2G的镜像会导致报错 
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (4974050632) out of range of int (-2147483648 - 2147483647)

另外 git repository里全局搜索了一下“Integer size” 发现还有不少 （如evs image） 是不是也考虑一下给改成Long呢

**Comment by Huaweicloud-SDK** [comment]
你好，SWR服务定义的size属性数据类型不合理问题已在3.0.34-rc版本中修改，查看 [变更日志](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/CHANGELOG_CN.md#huaweicloud-sdk-swr) 。
