### ISSUE TITLE
(Python)ProjectMan调用list_issues_v4接口报PARSE_REQUEST_DATA_EXCEPTION错误

### ISSUE THREAD

**Issue by kimsangbaek** [huaweicloud/huaweicloud-sdk-java-v3#29]
使用python SDK中的ProjectMan调用list_issues_v4接口报PARSE_REQUEST_DATA_EXCEPTION错误。
代码如下：
```
def list_project_issues(client:ProjectManClient, project_id):
    try:
        request = ListIssuesV4Request(project_id=project_id)
        response = client.list_issues_v4(request)
        print(response)
        return response
    except exceptions.RequestTimeoutException as e:
        print(e)
```

错误如下（为了保护，request_id用*代替）：
`huaweicloudsdkcore.exceptions.exceptions.ClientRequestException: ClientRequestException - {status_code:400,request_id:***********************,error_code:PARSE_REQUEST_DATA_EXCEPTION,error_msg:参数PARSE_REQUEST_DATA_EXCEPTION错误 }`

使用API Explorer不会有这个错误，通过CLI工具也会报同样的错误

**Comment by Christy11** [comment]
你好，我们确认了一下，这里是代码配置有些问题，这个接口的requestBody是要填的，您可以参考如下代码：

**Comment by kimsangbaek** [comment]
不好意思回复晚了，可以正常获得数据了，感谢！！！
