### ISSUE TITLE
Application/Data related operations vs Administrative operations 

### ISSUE THREAD

**Issue by hokutor** [huaweicloud/huaweicloud-sdk-java-v3#31]
Hello team

we were going over DCS sdk codebase. A lot of those operations looks like management/administrative in nature . 

We could like to use a sdk to perform cache operations like PUT, DELETE etc. Do you have plans to support such application/data related operations?  

Cheers

**Comment by wuchen-huawei** [comment]
Could you please describe your requirement more specifically? I've searched the DCS APIs in our SDK, we do have operations like PUT and DELETE, but I couldn't know which API you wanna use.

**Comment by wuchen-huawei** [comment]
I've asked the develop team about your requirement, unfortunately the answer is we don't support this kind of situation. You could try to use the SDK of open-source Redis Client instead.

**Comment by hokutor** [comment]
> I've asked the develop team about your requirement, unfortunately the answer is we don't support this kind of situation. You could try to use the SDK of open-source Redis Client instead.

Alright. Thanks for confirming. It was just a quick check before we decide on using the redis client. Appreciate your support :) 
Cheers
