### ISSUE TITLE
一个小小的拼写错误 BatchRebootSeversOption & ReinstallSeverMetadata

### ISSUE THREAD

**Issue by ridewind** [huaweicloud/huaweicloud-sdk-java-v3#32]
com.huaweicloud.sdk.ecs.v2.model.BatchRebootSeversOption 
应该是BatchRebootServersOption 吧 少了个r 

还有ReinstallSeverMetadata这个类也是 

不影响使用，就是看着怪怪的，改不改都行。

**Comment by wuchen-huawei** [comment]
您好，感谢您的建议。经过内部讨论，由于修复拼写错误会导致不兼容的修改，原本使用这个错误拼写方式调用的用户都会在新版本无法调用，且当前接口使用量较大影响面较广，所以这个拼写错误会保留。
