### ISSUE TITLE
ecs 过期时间获取不到

### ISSUE THREAD

**Issue by zhaihailong** [huaweicloud/huaweicloud-sdk-java-v3#33]

**Comment by wuchen-huawei** [comment]
你好，请问你这边是用的哪个接口？使用的是包周期的弹性云服务器吗？

**Comment by akhuang** [comment]
包周期相关的资源状态可通过BSS相关接口获取：
https://apiexplorer.developer.huaweicloud.com/apiexplorer/doc?product=BSS&api=ListPayPerUseCustomerResources

**Comment by mawenbo-huawei** [comment]
长时间未回复问题先关闭了，有问题请重新提交并附上清晰一些的描述
