### ISSUE TITLE
BUG : FunctionGraph response object mapping issue

### ISSUE THREAD

**Issue by hokutor** [huaweicloud/huaweicloud-sdk-java-v3#34]
We are trying to use sdk's function graph client to invoke a function. We are trying to use invokeFunction operation in the client. 

You can see the code snippet below as how we invoke the function

![image](https://user-images.githubusercontent.com/81697586/118878315-6d7a6680-b8bd-11eb-812a-2395d49efc38.png)

I have attached the response listener to the http configuration. The application log looks like follows

```log
[                          main] FGClient                       INFO  RESPONSE: POST 
https://functiongraph.cn-north-1.myhuaweicloud.com/v2/****project_id_masked******/fgs/functions/urn:fss:cn-north-1:****project_id_masked******:function:ROMA:CreateOrder:latest/invocations  
200  
Connection : Keep-Alive;Content-Length : 249;Content-Type : text/plain;Date : Wed, 19 May 2021 19:54:25 GMT;Server : api-gateway;Strict-Transport-Security : max-age=31536000; includeSubdomains;;via : proxy A;X-Cff-Invoke-Summary : {"funcDigest":"*****","duration":7.894,"billingDuration":100,"memorySize":128,"memoryUsed":64.390625};X-Cff-Request-Id : *******-a673-4970-837d-********;X-Cff-Result-Length : 249;X-Content-Type-Options : nosniff;X-Download-Options : noopen;X-Frame-Options : SAMEORIGIN;X-Request-Id : ******;X-XSS-Protection : 1; mode=block;  
{"headers":{"Content-Type":"application/json"},"statusCode":200,"isBase64Encoded":false,"body":{"orderId":1621454065815,"department":"sales","vendor":"huawei","product":"monitors","price":20.13,"quantity":20,"status":"order submitted successfully"}}
[                          main] HuaweiCloud-SDK-Access         INFO  "POST https://functiongraph.cn-north-1.myhuaweicloud.com/v2/****project_id_masked******/fgs/functions/urn:fss:cn-north-1:****project_id_masked******:function:ROMA:CreateOrder:latest/invocations" 200 249 f6b9493b2d7595ad89d4bdb2cfaf06b6 2876
[                          main] FGClient                       INFO  Invoke function results {} null
[                          main] FGClient                       INFO  Invoke function results {} class InvokeFunctionResponse {
    requestId: null
    result: null
    log: null
    status: null
}

```

We noted that the response json is not getting properly mapped to response object `InvokeFunctionResponse`. On debugging, following are our observations

- Original json response
```json
 {"headers":{"Content-Type":"application/json"},"statusCode":200,"isBase64Encoded":false,"body":{"orderId":1621449598595,"department":"sales","vendor":"huawei","product":"monitors","price":20.13,"quantity":20,"status":"order submitted successfully"}}
```

In [HcClient](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/core/src/main/java/com/huaweicloud/sdk/core/HcClient.java#L349) , an attempt to construct the object of [InvokeFunctionResponse](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/services/functiongraph/src/main/java/com/huaweicloud/sdk/functiongraph/v2/model/InvokeFunctionResponse.java) from the above response json is [done here](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/core/src/main/java/com/huaweicloud/sdk/core/HcClient.java#L349). The object constructed has null value in all class members because json object isn't compatible with model class.

**Comment by hokutor** [comment]
Debug screenshot

![sdk_debug](https://user-images.githubusercontent.com/81697586/118877615-a7973880-b8bc-11eb-8396-f96b5748cf2d.png)

**Comment by wangnengyuan** [comment]
please add withXCffLogType and withXCFFRequestVersion behind new InvokeFunctionRequest()  like this and just have a try:
new InvokeFunctionRequest().withXCffLogType("tail")
                    .withXCFFRequestVersion("v1")

**Comment by hokutor** [comment]
Alright. thanks. it works great. Looks like the key here is the version v1.
