### ISSUE TITLE
com.huaweicloud.sdk.rds.v3.model.Flavor  缺少 support_compute_group_type 属性

### ISSUE THREAD

**Issue by liudi2991** [huaweicloud/huaweicloud-sdk-java-v3#36]
Java SDK 版本3.0.46
com.huaweicloud.sdk.rds.v3.model 包中的 Storage 类 缺少 support_compute_group_type 属性，无法根据磁盘类型判断可以使用的性能规格

**Comment by wuchen-huawei** [comment]
你好，这个问题再最新的 3.0.47 版本已修复，请确认问题是否已经解决~
