### ISSUE TITLE
Support for token based auth

### ISSUE THREAD

**Issue by hokutor** [huaweicloud/huaweicloud-sdk-java-v3#37]
Hello @wuchen-huawei 

Currently, we see you support two kind of auth
1. Permanent Ak/Sk - we have been using this and works well
2. Token + AK/SK - Would like to know if we can auth without AK/SK here. Most of the cloud service rest api spec allow authentication via IAM user tokens alone. Is that supported in java SDK v3?

**Comment by wuchen-huawei** [comment]
Hello @hokutor , during the design of the SDK v3, we've confirmed that authentication via IAM user token wouldn't be supported, and it's more secure using AK/SK.
