### ISSUE TITLE
3.0.51版本新加的__lazyloading属性类型错误

### ISSUE THREAD

**Issue by ridewind** [huaweicloud/huaweicloud-sdk-java-v3#40]
com.huaweicloud.sdk.ims.v2.model.ImageInfo lazyloading属性 api返回的response里是字符串“True” 属性的类型是Boolean JSON转换时报错

**Comment by Huaweicloud-SDK** [comment]
你好，你反馈的问题已经在 3.0.52 版本修复，可查看[变更日志](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/CHANGELOG_CN.md#huaweicloud-sdk-ims)，如您在使用上还有问题，请提交issue或者在华为云控制台上提交工单。
