### ISSUE TITLE
vod视频点播无法上传视频

### ISSUE THREAD

**Issue by xiaokan001** [huaweicloud/huaweicloud-sdk-java-v3#41]
官方示例第一个方法不存在

**Comment by mawenbo-huawei** [comment]
你好，请提供一下不存在的方法名称，谢谢！

**Comment by Huaweicloud-SDK** [comment]
您好，我们已经很长时间没有收到您的回复，所以我们将关闭当前问题。如果您在使用我们的SDK时仍有问题，您可以重新打开该问题或在华为云控制台上创建工单。
