### ISSUE TITLE
DMS SDK for RabbitMQ and Kafka

### ISSUE THREAD

**Issue by hokutor** [huaweicloud/huaweicloud-sdk-java-v3#42]
Hi, I was wondering if there is any support for RabbitMQ and Kafka instance management in the DMS SDK? If not, is there a plan to add this in the future?

**Comment by mathewsreji** [comment]
@wuchen-huawei would love to hear more on this.

**Comment by mawenbo-huawei** [comment]
Refer to https://console-intl.huaweicloud.com/apiexplorer/#/openapi/Kafka/doc?api=BatchDeleteGroup
