### ISSUE TITLE
OCR SDK 识别电子驾照解析错误BUG

### ISSUE THREAD

**Issue by zwj1994** [huaweicloud/huaweicloud-sdk-java-v3#49]
OCR 电子驾照api接口返回json格式与sdk中的不一致导致报错
解析出错字段 status
json 返回的是 status: ["xxx"] xxx是字符串
sdk中对应的status 定义为 private List[DriverLicenseResultStatus]  status
DriverLicenseResultStatus是对象，和字符串类型不一致
![image](https://user-images.githubusercontent.com/24381883/165229373-ee2fb7cf-d7ae-4e06-b492-6563b422f154.png)

**Comment by mawenbo-huawei** [comment]
问题已在新版本`3.0.86`修复
