### ISSUE TITLE
3.1.34版本发布是个错误的版本

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/huaweicloud-sdk-java-v3#60]
Could not find artifact com.huaweicloud.sdk:huaweicloud-sdk-core:jar:3.1.34 in central (https://repo.maven.apache.org/maven2

**Comment by mawenbo-huawei** [comment]
查了一下是有的 https://repo.maven.apache.org/maven2/com/huaweicloud/sdk/huaweicloud-sdk-core/3.1.34/
本地也能依赖到，建议检查一下自己本地的maven配置

**Comment by Dramatic-z** [comment]
显示的有，但是下载不了：https://repo.huaweicloud.com/repository/maven/com/huaweicloud/sdk/huaweicloud-sdk-core/3.1.34/huaweicloud-sdk-core-3.1.34.jar
https://repo.maven.apache.org/maven2/com/huaweicloud/sdk/huaweicloud-sdk-core/3.1.34/huaweicloud-sdk-core-3.1.34.jar

**Comment by liubao68** [comment]
setting配置是没错的。 而且3.1.34只有这个组件无法下载，其他组件是可以的。 估计是maven发布哪儿出了点问题，现在中央仓可以看到和下载了。 提问题的时候，是看不到的。
