### ISSUE TITLE
bug-当调用发生错误时，这里有类型转换错误

### ISSUE THREAD

**Issue by Lijiaqi1992** [huaweicloud/huaweicloud-sdk-java-v3#61]
![image](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/assets/52096822/14a922f3-144a-4acb-a287-a7e0252169d3)
最近提交版本：v3.1.33

**Comment by mawenbo-huawei** [comment]
请问您调用的哪个服务的哪一个接口？ 可以的话，能贴上错误信息更好，例如：
```json
{
    "code":"",
    "message":""
}
```

**Comment by Lijiaqi1992** [comment]
> 请问您调用的哪个服务的哪一个接口？ 可以的话，能贴上错误信息更好，例如：
> 
> ```json
> {
>     "code":"",
>     "message":""
> }
> ```

调用的是”通过token获取临时访问密钥和securitytoken“，这个问题调用哪个接口不重要了，当调用发生异常，比如401，或403时，errResult的格式为：`{
    "code":403,
    "message":"xxx"
}`  由于前面使用了String 强转，所以会报Integer不能转为String的异常

**Comment by mawenbo-huawei** [comment]
由于返回的code字段应该是标准的字符串，所以这里强转string，这里会跟云服务接口对齐处理一下

**Comment by mawenbo-huawei** [comment]
该问题在[v3.1.55](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/releases/tag/v3.1.55)中已修复。
