### ISSUE TITLE
请问分布式服务，鉴权token如何存储，官方SDK示例是存在AbstractCredentials当中。

### ISSUE THREAD

**Issue by yichengxian** [huaweicloud/huaweicloud-sdk-java-v3#63]
官方文档鉴权文档: https://support.huaweicloud.com/api-ocr/ocr_03_0005.html
示例文档中 "Token的有效期为24小时，需要使用一个Token鉴权时，可以先缓存起来，避免频繁调用。"

而对应SDK代码示例中 直接将获得得token存入AbstractCredentials属性authToken中，
请问官方获取token不会失效到上一个token，如果不会失效是否会可以多服务分别使用不同得token，调用token是否有次数限制？
能否出局一份合理的使用意见

**Comment by mawenbo-huawei** [comment]
SDK不支持token认证方式，AbstractCredentials中的authToken是用于联邦认证的，参考https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/README_CN.md#23-%E4%BD%BF%E7%94%A8-idpid-%E5%92%8C-idtokenfile-top
