### ISSUE TITLE
创建弹性公网IP接口调用报错

### ISSUE THREAD

**Issue by top-code** [huaweicloud/huaweicloud-sdk-java-v3#7]
测试代码如下：
CreatePublicipRequest request = new CreatePublicipRequest();
        request.withBody(new CreatePublicip()
                .withPublicip(new PublicipsPublicipDict().withType("5_bgp"))
                .withBandwidth(new PubicipBandwidthDict().withShareType(PubicipBandwidthDict.ShareTypeEnum.WHOLE))); CreatePublicipResponse response = helper.getEipClient().createPublicip(request);

错误如下所示：
2020-07-20 10:13:08.619  INFO 2940 --- [           main] HuaweiCloud-SDK-Access                   : "POST https://vpc.cn-north-4.myhuaweicloud.com/v1/08aa44f14d00f46d2f41c015b69d6ebf/publicips" 400 143 3ddda4316f32931142c9d143f8b0c76d
2020-07-20 10:13:08.639 ERROR 2940 --- [           main] com.huaweicloud.sdk.core.HcClient        : ServiceResponseException occurred. Host: vpc.cn-north-4.myhuaweicloud.com Uri: https://vpc.cn-north-4.myhuaweicloud.com/v1/08aa44f14d00f46d2f41c015b69d6ebf/publicips ServiceResponseException: com.huaweicloud.sdk.core.exception.SdkErrorMessage@24e1e90a

ClientRequestException {
    httpStatusCode: 400
    errorCode: VPC.0501
    errorMsg: {"NeutronError":{"message":"Bandwidth share_type is invalid.","type":"InvalidInput","detail":""}}

    requestId: 3ddda4316f32931142c9d143f8b0c76d
}
错误信息显示带宽的类型非法，但参数均是按照SDK指定的类型添加。

**Comment by zhic5352** [comment]
share_type 当此字段指定为WHOLE时表示指定共享带宽创建弹性公网IP，需要同时指定带宽的id；  
可以参考官网文档： [申请弹性公网ip](https://support.huaweicloud.com/api-eip/eip_api_0001.html)      
![image](https://user-images.githubusercontent.com/9360943/87895257-85a01000-ca77-11ea-9ed1-7985ab7f2f43.png)

**Comment by top-code** [comment]
> share_type 当此字段指定为WHOLE时表示指定共享带宽创建弹性公网IP，需要同时指定带宽的id；
> 可以参考官网文档： [申请弹性公网ip](https://support.huaweicloud.com/api-eip/eip_api_0001.html)
> ![image](https://user-images.githubusercontent.com/9360943/87895257-85a01000-ca77-11ea-9ed1-7985ab7f2f43.png)

选择共享带宽时，指定的带宽id必须是已经存在的吗？

**Comment by zhic5352** [comment]
> > share_type 当此字段指定为WHOLE时表示指定共享带宽创建弹性公网IP，需要同时指定带宽的id；
> > 可以参考官网文档： [申请弹性公网ip](https://support.huaweicloud.com/api-eip/eip_api_0001.html)
> > ![image](https://user-images.githubusercontent.com/9360943/87895257-85a01000-ca77-11ea-9ed1-7985ab7f2f43.png)
> 
> 选择共享带宽时，指定的带宽id必须是已经存在的吗？

是的，选择WHOLE时需要先创好共享带宽，可以参考[创建共享带宽](https://support.huaweicloud.com/api-eip/eip_apisharedbandwidth_0001.html)，然后再指定这个带宽的id[申请弹性公网IP](https://support.huaweicloud.com/api-eip/eip_api_0001.html)，如果和弹性公网IP新创带宽，可以选择PER类型。

**Comment by top-code** [comment]
好的  了解了   多谢！
