### ISSUE TITLE
SM签名算法有潜在风险

### ISSUE THREAD

**Issue by icloudice** [huaweicloud/huaweicloud-sdk-java-v3#71]
protected SM3AKSKSigner() {
        super();
        this.algorithm = Constants.SDK_HMAC_SM3;
        this.contentHeader = Constants.X_SDK_CONTENT_SM3;
        this.emptyHash = "1ab21d8355cfa17f8e61194831e81a8f22bec8c728fefb747ed035eb5082aa2b";
        this.hasher = new SM3Hasher();
    }

    public static SM3AKSKSigner getInstance() {
        if (instance != null) {
            return instance;
        }

        synchronized (SM3AKSKSigner.class) {
            if (instance == null) {
                Security.addProvider(new BGMProvider());
                instance = new SM3AKSKSigner();
            }
            return instance;
        }
    }

这里虽然加载了provider。但是实际hash运算的时候没有指定provider。
该问题会造成以下风险：当其他业务有其他实现了SM3的HASH或者HMAC算法时。并且指定provider顺序高于Security.addProvider(new BGMProvider());加载顺序，会造成使用其他业务实现的SM3的HASH或者HMAC算法。造成SDK执行行为受业务影响。对于下面这段代码：SM3Digest digest = new SM3Digest();不会受影响。而Mac mac = Mac.getInstance(HMAC_SM3);则会受影响。

class SM3Hasher extends AbstractHasher {

    private static final String HMAC_SM3 = "HmacSM3";

    @Override
    protected byte[] hash(byte[] data) {
        SM3Digest digest = new SM3Digest();
        digest.update(data, 0, data.length);
        byte[] hash = new byte[digest.getDigestSize()];
        digest.doFinal(hash, 0);
        return hash;
    }

    @Override
    protected byte[] hmac(byte[] data, byte[] key) {
        try {
            Mac mac = Mac.getInstance(HMAC_SM3);
            mac.init(new SecretKeySpec(key, HMAC_SM3));
            return mac.doFinal(data);
        } catch (InvalidKeyException | NoSuchAlgorithmException e) {
            throw new SdkException("Unable to calculate a request signature", e);
        }
    }
}

**Comment by mawenbo-huawei** [comment]
感谢您的反馈！将在下个版本修复该问题。

**Comment by mawenbo-huawei** [comment]
该问题已修复，参考[ release v3.1.79](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/releases/tag/v3.1.79)
