### ISSUE TITLE
弹性公网IP绑定资源的API未找到

### ISSUE THREAD

**Issue by top-code** [huaweicloud/huaweicloud-sdk-java-v3#8]
没有找到弹性公网IP绑定资源的API 以及SDK。
查询指定的弹性公网IP接口返回的数据中也没有绑定资源的相关信息，建议添加。

**Comment by zhic5352** [comment]
可以使用更新接口绑定/解绑弹性公网IP  
参考官网文档：[更新弹性公网IP](https://support.huaweicloud.com/api-eip/eip_api_0004.html)    
![image](https://user-images.githubusercontent.com/9360943/87895424-fe06d100-ca77-11ea-91d3-dc32fd7089d0.png)
